### ISSUE TITLE
How to add text to each item?

### ISSUE THREAD

**Issue by eternalBlast** [mmoamenn/LuckyWheel_Android#1]
Hello, this is a great library. It can attach image to each element in the wheel. But, how to add text to each item like +2 coins or something like that?  And how to stop it like call the stop() function? Thanks in advance.

**Comment by mmoamenn** [comment]
Hello , First of all thank you for feedback, Adding text not covered in this version but i will work to add this feature in the next one and for stop wheel just call function --rotateWheelTo(2);-- to stop wheel at position.

Regards,

**Comment by eternalBlast** [comment]
Hi @mmoamenn thanks for your response. I mean stop when the wheel is spinning. So, the user tap the play and the wheel begin to spin. When the wheel is spinning the play button become the stop button. When the user tap the stop button, it slowly stop the spinning. Thanks.

**Comment by MFlisar** [comment]
Added this in my pull request...

**Comment by mmoamenn** [comment]
kindly user the latest version
