### ISSUE TITLE
[Improvement] Rotate text

### ISSUE THREAD

**Issue by dphans** [mmoamenn/LuckyWheel_Android#11]
Hopefully this library support no bitmap data and rotate text like photo below <3
![custom – 1](https://user-images.githubusercontent.com/12996976/60395026-74781e80-9b57-11e9-8aac-a90c401cae1c.png)

**Comment by mmoamenn** [comment]
thank you I will add it to back-log

**Comment by NStreet8579** [comment]
@mmoamenn When can we get enhancement?

**Comment by mmoamenn** [comment]
it's fixed now use the latest release

**Comment by rahmanarifofficial** [comment]
How to use the "Rotate Text" feature in your latest release?

**Comment by MarioRangel7AM** [comment]
this feature was released yet ?
