### ISSUE TITLE
Unknown attribute

### ISSUE THREAD

**Issue by SolDiez90** [mmoamenn/LuckyWheel_Android#13]
Unknown attribute LuckyWheel:background_color.

<com.bluehomestudio.luckywheel.LuckyWheel
        android:id="@+id/lwv"
        android:layout_width="310dp"
        android:layout_height="310dp"
        android:layout_centerInParent="true"
        android:layout_marginTop="56dp"
        LuckyWheel:background_color="@color/colorPrimary"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.495"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/turnText" />

**Comment by amit517** [comment]
I also facing the same problem.

**Comment by Ansari1221** [comment]
I think you should use direct color value like #XXXXXX don't use '@color/color_name'  okay.... Try this one... It will work

**Comment by mhkarami** [comment]
use `xmlns:LuckyWheel="http://schemas.android.com/apk/res-auto"` in your `xml` file main layout :
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:LuckyWheel="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.luckywheel.LuckyWheelActivity">
```

**Comment by mmoamenn** [comment]
use @mhkarami solution
