### ISSUE TITLE
README.md instructions result in broken code

### ISSUE THREAD

**Issue by mikeblas** [mmoamenn/LuckyWheel_Android#22]
Steps to Repro:

1. In Android Studio, create a new "Empty Activity" project
2. Per the LuckyWheel `README.md`, add the dependencies to the Gradle scripts
3. Open the `activity_main.xml` layout resource and add the XML block from the LuckyWheel `README.md` instructions

**BUG:** The build fails with the message "`app\src\main\res\layout\activity_main.xml:18: AAPT: error: unbound prefix.`"

It seems like the fix is to remove the `background_color` attribute, so the XML block looks like this:

```
<com.bluehomestudio.luckywheel.LuckyWheel
        android:id="@+id/lwv"
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_centerInParent="true" />
```

but that means that we can't access LuckyWheel attributes in the XML settings. My guess is that a new XML namespace must be imported, but the `README.md` doesn't mention that before recommending the qualified XML attributes, and doesn't explain how to do the import.

Maybe the `README.md` should be changed to not mention the broken properties. Or, maybe it should offer complete instructions that show how to make them work correctly.

**Comment by mikeblas** [comment]
Maybe this is related to item #13. Looks like @mhkarami there explains how to add the required namespace. I think it would be helpful if that advice were added to `README.md`.

**Comment by FranH20** [comment]
Yo lo solucione con esta línea en el layout padre
`xmlns:LuckyWheel="http://schemas.android.com/apk/res-auto"`

**Comment by FranH20** [comment]
I solved it with this line in the parent layout
Yo lo solucione con esta línea en el layout padre
`xmlns:LuckyWheel="http://schemas.android.com/apk/res-auto"`

**Comment by mikeblas** [comment]
Why is this closed? The README hasn't been fixed.
